# dedicated image with python 3.9 installed
image:
  file: .gitpod.dockerfile

tasks:
  - before: |
      export FLASK_APP=yaptide.application
      export FLASK_ENV=development
    init: |
      pip install -r requirements.txt
    command: |
      flask run
vscode:
  extensions:
    - ms-python.python