# dedicated image with python 3.9 installed
image:
  file: .gitpod.dockerfile

tasks:
  - before: |
      export FLASK_APP=yaptide.application
      export FLASK_DEBUG=1
    init: |
      export POETRY_VIRTUALENVS_CREATE=false
      export FLASK_SQLALCHEMY_DATABASE_URI=sqlite:///yaptide/main.db
      pip install poetry && poetry install --only main
    command: |
      poetry run flask run
vscode:
  extensions:
    - ms-python.python
