FROM python:3.10-slim
WORKDIR /usr/local/app

# install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# copy project
COPY yaptide ./yaptide
