services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yaptide_pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "9999:80"
    depends_on:
      - postgresql
