# Stage 1: Generate SSL certificate
FROM alpine AS cert-gen

RUN apk add --no-cache openssl

WORKDIR /certs

RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
    -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost" \
    -keyout server.key -out server.crt


# Stage 2: Serve the nginx proxy
FROM nginx:1.25-alpine

# Configure Nginx to serve as the proxy
RUN rm /etc/nginx/conf.d/default.conf


# Copy SSL certificate from the build stage
COPY --from=cert-gen /certs /etc/nginx/conf.d

# Copy the Nginx configuration
COPY nginx.conf /etc/nginx/conf.d
RUN chown -R 1000730000:1000730000 /etc/nginx
RUN chown -R 1000730000:1000730000 /var
RUN chmod 700 -R /var
RUN chmod 700 -R /etc/nginx

EXPOSE 5000

CMD ["nginx", "-g", "daemon off;"]