FROM python:3.10-slim

# add directory /usr/local/simulators to PATH
ENV PATH="/usr/local/simulators:${PATH}"

# install dependencies
WORKDIR /usr/local/app
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

# copy project
COPY yaptide ./yaptide

# run app via `celery --app yaptide.celery.worker worker -P threads --loglevel=info`
CMD ["celery", "--app", "yaptide.celery.worker", "worker", "-P", "threads", "--loglevel=info"]
