FROM python:3.12-slim
ARG POETRY_VERSION=1.8.2

# expose port to run Flask
EXPOSE 6000

# set environment variables
ENV FLASK_APP=yaptide.application
WORKDIR /usr/local/app

# Copy poetry configuration files
COPY poetry.lock poetry.toml pyproject.toml ./
# Install poetry and project dependencies, we also disabled virtualenv creation
ENV POETRY_VIRTUALENVS_CREATE=false
RUN pip install --no-cache-dir poetry==$POETRY_VERSION && poetry install --only main

# copy project
COPY yaptide ./yaptide

# copy .gitsubmodules file to check if submodules are cloned correctly
COPY .gitmodules ./

# Some of our developers use Windows to run Docker, their bash scripts have CRLF line endings
# therefore when copied to the container they are not executable. This is a workaround to fix that.
# skipcq: DOK-W1001
RUN python -c "import os; content = open('yaptide/admin/db_manage.py', 'rb').read().replace(b'\r\n', b'\n'); open('yaptide/admin/db_manage.py', 'wb').write(content)"

# Health check using Python and requests, we are not using curl or wget as they are not installed by default
HEALTHCHECK CMD python -c "import requests; exit(0) if requests.get('http://localhost:6000/').ok else exit(1)"

# Run Flask app
ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=6000"]
