# Stage 1: Generate SSL certificate
FROM alpine AS cert-gen

RUN apk add --no-cache openssl

WORKDIR /certs

RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
    -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost" \
    -keyout server.key -out server.crt


# Stage 2: Serve the nginx proxy
FROM nginx:1.25-alpine

# Configure Nginx to serve as the proxy
RUN rm /etc/nginx/conf.d/default.conf


# Copy SSL certificate from the build stage
COPY --from=cert-gen /certs /etc/nginx/conf.d

# Copy the Nginx configuration
COPY ./nginx.conf.template /nginx.conf.template

# Permission fixes
RUN chown -R 1000730000:1000730000 /etc/nginx && \
    chown -R 1000730000:1000730000 /var && \
    chown -R 1000730000:1000730000 /run && \
    chmod 700 -R /var && \
    chmod 700 -R /etc/nginx && \
    chmod 700 -R /run

EXPOSE 5000

CMD ["/bin/sh" , "-c" , "envsubst < /nginx.conf.template > /etc/nginx/conf.d && exec nginx -g 'daemon off;'"]