# Enhanced Startup Configuration:
# Requires Docker Engine v25 (2024-01-19). Modifies healthcheck frequency for improved startup times.
# Initial healthchecks every 5 seconds for the first 30 seconds post-container launch to mitigate delays from container dependencies.
# Post-initial period, healthchecks revert to standard 30-second intervals.


services:
  redis:
    healthcheck:
      start_period: 30s
      start_interval: 5s

  postgresql:
    healthcheck:
      start_period: 30s
      start_interval: 5s

  yaptide_flask:
    healthcheck:
      start_period: 30s
      start_interval: 5s

  yaptide_simulation_worker:
    healthcheck:
      start_period: 60s
      start_interval: 5s

  yaptide_helper_worker:
    healthcheck:
      start_period: 30s
      start_interval: 3s
