FROM python:3.10-slim

# install gfortran via apt and clean cache
# skipcq: DOK-DL3008
RUN apt-get update && apt-get install -y --no-install-recommends gfortran && rm -rf /var/lib/apt/lists/*

# set working directory
WORKDIR /usr/local/app

# openshift permissions
RUN chgrp -R 0 /usr/local/app && \
    chmod -R g=u /usr/local/app

# install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY yaptide ./yaptide

# set max task time to 10 hours
ENV CELERYD_TIME_LIMIT=36000

# add path where shieldhit will be installed
ENV PATH="/usr/local/app/bin:${PATH}"

# Copy worker script
COPY run_worker.sh .

# Convert line endings using Python
RUN python3 -c "import os; content = open('run_worker.sh', 'rb').read().replace(b'\r\n', b'\n'); open('run_worker.sh', 'wb').write(content)"
RUN python3 -c "import os; content = open('yaptide/admin/simulators.py', 'rb').read().replace(b'\r\n', b'\n'); open('yaptide/admin/simulators.py', 'wb').write(content)"

# Make the scripts executable
RUN chmod +x run_worker.sh yaptide/admin/simulators.py

# Set the script as the entry point
ENTRYPOINT ["bash", "run_worker.sh"]