FROM python:3.10-slim

# set environment variables
ENV FLASK_APP=yaptide.redis_consumers.application
WORKDIR /usr/local/app

# install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY yaptide ./yaptide
ENV PYTHONPATH=${PYTHONPATH}:.

# Some of our developers use Windows to run Docker, their bash scripts have CRLF line endings
# therefore when copied to the container they are not executable. This is a workaround to fix that.
# skipcq: DOK-W1001
RUN python -c "import os; content = open('yaptide/admin/db_manage.py', 'rb').read().replace(b'\r\n', b'\n'); open('yaptide/admin/db_manage.py', 'wb').write(content)"

# Run Flask app
ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=7000"]