"""empty message

Revision ID: 06c32cf470e7
Revises: 
Create Date: 2024-10-17 14:51:34.581095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c32cf470e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'auth_provider', name='_username_provider_uc')
    )
    op.create_table('KeycloakUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert', sa.String(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('sim_type', sa.String(), nullable=False),
    sa.Column('job_state', sa.String(), nullable=False),
    sa.Column('update_key_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('YaptideUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BatchSimulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('job_dir', sa.String(), nullable=True),
    sa.Column('array_id', sa.Integer(), nullable=True),
    sa.Column('collect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['Cluster.id'], ),
    sa.ForeignKeyConstraint(['id'], ['Simulation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CelerySimulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merge_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Simulation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Estimator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('compressed_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['Simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('compressed_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['Simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Logfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('compressed_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['Simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('requested_primaries', sa.Integer(), nullable=False),
    sa.Column('simulated_primaries', sa.Integer(), nullable=False),
    sa.Column('task_state', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('last_update_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['Simulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'task_id', name='_simulation_id_task_id_uc')
    )
    op.create_table('BatchTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CeleryTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimator_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('compressed_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['estimator_id'], ['Estimator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Page')
    op.drop_table('CeleryTask')
    op.drop_table('BatchTask')
    op.drop_table('Task')
    op.drop_table('Logfiles')
    op.drop_table('Input')
    op.drop_table('Estimator')
    op.drop_table('CelerySimulation')
    op.drop_table('BatchSimulation')
    op.drop_table('YaptideUser')
    op.drop_table('Simulation')
    op.drop_table('KeycloakUser')
    op.drop_table('User')
    op.drop_table('Cluster')
    # ### end Alembic commands ###
