"""empty message

Revision ID: 3dd069fbf2d2
Revises: 5003b9acb1f4
Create Date: 2024-12-14 15:20:05.145783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd069fbf2d2'
down_revision = '5003b9acb1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CeleryTask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_pid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('path_to_sim', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CeleryTask', schema=None) as batch_op:
        batch_op.drop_column('path_to_sim')
        batch_op.drop_column('sim_pid')

    # ### end Alembic commands ###
