"""empty message

Revision ID: 4027fc5cbcb1
Revises: 3f9d1f1bec46
Create Date: 2024-10-29 13:19:10.523163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4027fc5cbcb1'
down_revision = '3f9d1f1bec46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Simulation', schema=None) as batch_op:
        batch_op.drop_column('update_key_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Simulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_key_hash', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
