"""empty message

Revision ID: 5003b9acb1f4
Revises: 41149fa64bd2
Create Date: 2024-12-10 22:51:14.262553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
import logging
from yaptide.persistence.models import PageModel


# revision identifiers, used by Alembic.
revision = '5003b9acb1f4'
down_revision = '41149fa64bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_name', sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('page_dimension', sa.Integer(), nullable=False, server_default="0"))
    
    bind = op.get_bind()
    session = sessionmaker(bind=bind)()
    
    pages = session.query(PageModel).all()
    
    for page in pages:
        page_data = page.data
        if not page_data:
            logging.warning('Missing page data for page ID = %s', page.id)
        else:
            page.page_dimension=int(page_data['dimensions'])
            page.page_name=str(page_data["metadata"]["name"])
    
    session.commit()
    session.close()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Page', schema=None) as batch_op:
        batch_op.drop_column('page_dimension')
        batch_op.drop_column('page_name')

    # ### end Alembic commands ###
