"""empty message

Revision ID: bb893eb0d961
Revises: 41149fa64bd2
Create Date: 2024-12-12 17:11:48.551898

"""
import logging
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from yaptide.persistence.models import TaskModel


# revision identifiers, used by Alembic.
revision = 'bb893eb0d961'
down_revision = '41149fa64bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_pid', sa.Integer(), nullable=False, server_default=sa.text("-1")))
        batch_op.add_column(sa.Column('path_to_sim', sa.String(), nullable=False, server_default=""))
    bind = op.get_bind()
    session = sessionmaker(bind=bind)()

    tasks = session.query(TaskModel).all()
    try:
        for task in tasks:
            if task.path_to_sim is None:
                task.path_to_sim = ''
            if task.sim_pid is None:
                task.sim_pid = -1
    except Exception as e:
        logging.warning(f"Failed to migrate path_to_sim and sim_pid for task with id {task.id}: {e}")  
    session.commit()
    session.close()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_column('path_to_sim')
        batch_op.drop_column('sim_pid')

    # ### end Alembic commands ###
