"""Add port column to cluster

Revision ID: d0a89a16fbac
Revises: 5003b9acb1f4
Create Date: 2026-07-30 15:32:48.414185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a89a16fbac'
down_revision = '5003b9acb1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cluster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cluster', schema=None) as batch_op:
        batch_op.drop_column('port')

    # ### end Alembic commands ###
