name: Retention policy for worker and flask packages

on:
  schedule:
    - cron: '30 4 * * MON'
  workflow_dispatch:

jobs:
  cleanup-packages:
    name: Cleanup old packages
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup flask and worker old PR packages
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ github.event.repository.name }}-flask, ${{ github.event.repository.name }}-worker
          cut-off: 2 weeks ago UTC
          timestamp-to-use: created_at
          account-type: org
          org-name: ${{ github.repository_owner }}
          keep-at-least: 0
          untagged-only: true
          token: ${{ secrets.PAT }}
          dry-run: true
      - name: Cleanup flask and worker old master packages
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ github.event.repository.name }}-flask, ${{ github.event.repository.name }}-worker
          cut-off: 1 month ago UTC
          timestamp-to-use: created_at
          account-type: org
          org-name: ${{ github.repository_owner }}
          keep-at-least: 0
          filter-include-untagged: false
          filter-tags: master-*
          skip-tags: master # Don't remove the newest master image
          token: ${{ secrets.PAT }}
          dry-run: true
